-- MySQL Script generated by MySQL Workbench
-- Fri Jun 25 09:06:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_petshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_petshop` DEFAULT CHARACTER SET utf8 ;
USE `db_petshop` ;

-- -----------------------------------------------------
-- Table `db_petshop`.`permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petshop`.`permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_petshop`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petshop`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NULL,
  `nome_user` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cd` TIMESTAMP NULL,
  `ud` TIMESTAMP NULL,
  `idpermissao` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_permissao_idx` (`idpermissao` ASC),
  CONSTRAINT `fk_usuario_permissao`
    FOREIGN KEY (`idpermissao`)
    REFERENCES `db_petshop`.`permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_petshop`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petshop`.`cliente` (
  `ClienteID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100),
  `Telefone` VARCHAR(20),
  `Endereco` VARCHAR(200),
  PRIMARY KEY (`ClienteID`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_petshop`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petshop`.`animal` (
  `AnimalID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Especie` VARCHAR(50) NOT NULL,
  `Raca` VARCHAR(50),
  `Idade` INT,
  `ClienteID` INT,
  PRIMARY KEY (`AnimalID`),
  FOREIGN KEY (`ClienteID`) REFERENCES `db_petshop`.`cliente` (`ClienteID`)
)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `db_petshop`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petshop`.`produto` (
  `ProdutoID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Descricao` VARCHAR(200),
  `Preco` DECIMAL(10, 2) NOT NULL,
  `QuantidadeEmEstoque` INT NOT NULL,
  PRIMARY KEY (`ProdutoID`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_petshop`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petshop`.`venda` (
  `VendaID` INT NOT NULL AUTO_INCREMENT,
  `DataVenda` DATE NOT NULL,
  `ClienteID` INT,
  `Total` DECIMAL(10, 2) NOT NULL,
  PRIMARY KEY (`VendaID`),
  FOREIGN KEY (`ClienteID`) REFERENCES `db_petshop`.`cliente` (`ClienteID`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_petshop`.`item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petshop`.`item_venda` (
  `ItemID` INT NOT NULL AUTO_INCREMENT,
  `VendaID` INT NOT NULL,
  `ProdutoID` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  `PrecoUnitario` DECIMAL(10, 2) NOT NULL,
  PRIMARY KEY (`ItemID`),
  FOREIGN KEY (`VendaID`) REFERENCES `db_petshop`.`venda` (`VendaID`),
  FOREIGN KEY (`ProdutoID`) REFERENCES `db_petshop`.`produto` (`ProdutoID`)
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
